CREATE TABLE USERS
(
  USERID SERIAL PRIMARY KEY NOT NULL UNIQUE,
  USERNAME varchar(255)  NOT NULL UNIQUE,
  HASH varchar(255),
  SALT varchar(255)
);

CREATE TABLE PLATFORM
(
  PLATFORMID SERIAL PRIMARY KEY NOT NULL UNIQUE,
  PLATFORMNAME varchar(255) NOT NULL UNIQUE
);

CREATE TABLE PLATFORM_USERS
(
  PLATFORMID INT NOT NULL references PLATFORM(PLATFORMID),
  PLATFORMNAME varchar(255) NOT NULL references PLATFORM(PLATFORMNAME),
  USERID INT NOT NULL references USERS(USERID),
  ONOFF INT NOT NULL,
  FREQUENCY DOUBLE PRECISION,
  INTERESTS varchar(255),
  TOKEN varchar(255)
);

CREATE TABLE POSTS
(
  POSTID SERIAL PRIMARY KEY NOT NULL UNIQUE,
  USERID INT NOT NULL references USERS(USERID),
  PLATFORMID INT NOT NULL references PLATFORM(PLATFORMID),
  ONOFF INT NOT NULL,
  MESSAGE varchar(255),
  EXPIRES DATE
);